### ISSUE TITLE
Hotfix release needed - Issue with latest rxjs release candidate

### ISSUE THREAD

**Issue by redaxmedia** [alexanderGugel/ied#178]
Hello,

there is an issue with "rxjs@5.0.0-rc.2" that was released a day ago. This is going to break all IED released since 2.0.0 until 2.3.3. I suggest to release a hotfix as soon as possible. It is not a good idea to use a beta in combination with ^ in the version number - I hope someone learns a lesson from that :-)

**Error:**
Cannot find module 'rxjs/operator/distinctKey'

**Broken build:**
https://travis-ci.org/redaxmedia/redaxscript-download-sync/builds/173742057

Temporary solution is to install the earlier version of rxjs:
<pre>
- npm install --global ied
- npm install --global rxjs@5.0.0-rc.1
- ied install
</pre>

**Fixed build:**
https://travis-ci.org/redaxmedia/redaxscript-download-sync/builds/173776343

**Solution for package.json:**

<pre>"rxjs": "rxjs@5.0.0-rc.1"</pre>

* **Version**: latest
* **Platform**: Travis CI / Debian
* **Subsystem**: NodeJS 6.9.1

**Comment by alexanderGugel** [comment]
Awesome! Thanks.

Fix released as `ied@2.3.4`.

**Comment by redaxmedia** [comment]
This does not fix anything, because you are using ^ again... lol

**Comment by alexanderGugel** [comment]
This has been fixed because we're no longer using `distinctKey`, which has been removed from RxJS.

Unfortunately Node decided to break symlinks as of this PR: https://github.com/nodejs/node/pull/8749#issuecomment-258423665

This means package managers that make heavy use of symlinked dependencies won't work anymore.

**Comment by alexanderGugel** [comment]
To follow up, this is actually a bigger issue which would need to be addressed by using a different installation strategy that doesn't rely on symlinks.

**Comment by redaxmedia** [comment]
Let me understand this!? Doesn't this remove all the performance benefit of IED?

**Comment by alexanderGugel** [comment]
No, but we need to move away from symlinks.

I'm not happy about this either and I've been trying to prevent this change in Node from the start.

In fact, the issue addressing this is currently one of the [most-commented on issues](https://github.com/nodejs/node/issues/3402) on the Node issue tracker.

The fundamental problem is that Node used to identify required modules by their real path, rather by the path of their symlink.

Eventually the decision was made to use the path of the symlink for some rather obscure reasons. After this broke all kinds of packages (not just package managers like ied and [pnpm](https://github.com/rstacruz/pnpm/issues/244)), the PR was eventually [reverted](https://github.com/nodejs/node/pull/6721). To allow people to use the "new" behaviour, a new [flag was added](https://github.com/nodejs/node/commit/5d38d543cdd25962fadc49a997798d156a41e4c7).

**Comment by zkochan** [comment]
I think it is fine that it is on a flag for now. With enough time we will be able to prove how awesome is the concept of a shared storage for packages!

I did not see any plans about deprecating `--preserve-symlinks`. Just [this comment](https://github.com/nodejs/node/pull/8749#issuecomment-249571388)

However, even if they plan to do it, they will have to do it as a breaking change, so it'll be not sooner than in version 8. Hence we have like a year to make yarn/pnpm popular enough to be taken into account by the Node.js team.

That's why I'd really like to collaborate with you guys to maybe merge pnpm and yarn or have some shared core or specs... to unite forces so to say

**Comment by alexanderGugel** [comment]
Well, I don't think yarn and ied are going to merge [anytime soon](https://github.com/yarnpkg/yarn/pull/817). :neckbeard: 

That being said, I'm definitely open to the idea of merging pnpm into ied or vice versa. After all, pnpm started out as a fork of ied! So why not go back to the roots? ☀️

**Comment by zkochan** [comment]
haha, I've meant merging pnpm and ied.
