### ISSUE TITLE
Error: EXDEV, rename

### ISSUE THREAD

**Issue by jclulow** [alexanderGugel/ied#4]
Just tried `ied install restify` in an empty directory.  It failed almost immediately with:

```
$ ied install restify
[==============================] 100.00%/Users/jclulow/.node/node_modules/ied/lib/install_cmd.js:63
        if (err) throw err
                       ^
Error: EXDEV, rename '/var/folders/p3/dwph0qjj02g5fmxwmczcbpgc0000gn/T/11fc00f7-f718-4fc9-92a5-f0b451bff06d'
    at Error (native)
```

I haven't really dug into the code, but if we assume this is actually a `rename(2)` call, it is likely failing because you're trying to rename something from somewhere in `TMPDIR` to my working directory -- which happens to be on a different filesystem:

```
       EXDEV
                       The links named by old and new are on different file
                       systems.
```

(Node version `v0.12.7`, operating system is Mac OS X 10.11)

**Comment by alexanderGugel** [comment]
> I haven't really dug into the code, but if we assume this is actually a rename(2) call, it is likely failing because you're trying to rename something from somewhere in TMPDIR to my working directory -- which happens to be on a different filesystem:

Exactly. I'm not sure what the best way to solve this is.
The easiest way is to set the `IED_TMPDIR` environment variable to the temporary directory you want to use (which needs to be on the same filesystem).

**Comment by jclulow** [comment]
Why does it need to be on the same filesystem?  If you're assembling a directory tree to be moved atomically into place, you should probably be assembling it in the `node_modules` directory itself, not in some unrelated temporary directory.

**Comment by alexanderGugel** [comment]
Yup, will be fixed soon. We're going to move away from putting stuff into `TMPDIR` and use `node_modules/.tmp` instead. That should fix it.

**Comment by joshuataylor** [comment]
Perfect, this also seems to fail in docker. :)

**Comment by alexanderGugel** [comment]
Should be fixed now. Please let me know if you run into any other issues or if that fixed it for you!

Thanks!

**Comment by joshuataylor** [comment]
Perfect! This fixes the issue.

**Comment by digitalfiz** [comment]
I am still having this issue with 2.1.0.

I will note that this is in a docker container running as root. here is the error:

```
/usr/lib/node_modules/ied/node_modules/rxjs/Observer.js:5
    error: function (err) { throw err; },
                                  ^
Error: EXDEV, rename '/root/.ied_cache/.tmp/82c40171-0b4a-4c0f-acdf-5883bcd39790'
    at Error (native)
```
